### ISSUE TITLE
Missing description on this repo

### ISSUE THREAD

**Issue by dorchard** [nextsimhub/domain_decomp#51]
This repo could do with an 'about/ description' text on the GitHub.

**Comment by jwallwork23** [comment]
@TomMelt I think you have enough permissions to add this? Perhaps "Domain decomposition tool for the nextSIM-DG next-generation sea ice model"?

**Comment by TomMelt** [comment]
sadly, I do not :disappointed:  I will ask @timspainNERSC . 

@timspainNERSC , could you please add the description @jwallwork23 mentioned to this repo.

> Domain decomposition tool for the nextSIM-DG next-generation sea ice model

It will show up in the about section on the project's homepage:
![image](https://github.com/user-attachments/assets/cbb03abb-a106-4baf-b70f-1d078062fc0a)

**Comment by jwallwork23** [comment]
Thanks @timspainNERSC, will close the issue now.
